// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCk1Pn7Khz_lHHQsIoaySZQTWOSPLWiY',
    appId: '1:615993279243:web:41da3226f7fecc68b6580e',
    messagingSenderId: '615993279243',
    projectId: 'first-e96fa',
    authDomain: 'first-e96fa.firebaseapp.com',
    storageBucket: 'first-e96fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEAuTZ2ZgHwD2k3hJvzCMh_mMYikDKOrE',
    appId: '1:615993279243:android:aa93db6e1fb71710b6580e',
    messagingSenderId: '615993279243',
    projectId: 'first-e96fa',
    storageBucket: 'first-e96fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoaa69CB-a1Z1Q8S5YB73b__1ucmJtPzY',
    appId: '1:615993279243:ios:f3880e35a8d8d684b6580e',
    messagingSenderId: '615993279243',
    projectId: 'first-e96fa',
    storageBucket: 'first-e96fa.appspot.com',
    iosBundleId: 'com.example.crudfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoaa69CB-a1Z1Q8S5YB73b__1ucmJtPzY',
    appId: '1:615993279243:ios:9d530d9ffb877412b6580e',
    messagingSenderId: '615993279243',
    projectId: 'first-e96fa',
    storageBucket: 'first-e96fa.appspot.com',
    iosBundleId: 'com.example.crudfire.RunnerTests',
  );
}
